### ISSUE TITLE
User-based fixed token authentication

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#103]
In order to allow for proper integration into external sites and services, the backend needs to support "static" authentication on a per-user basis, for example via "user API tokens".
Users could generate these tokens in their account page and use them to perform actions on their behalf using third-party services (e.g. a community's internal mission tool).

-----

### Tasks
- [ ] API token model
- [ ] Endpoints for managing API tokens
- [ ] Adaption to authentication strategy to accept API tokens and retrieve user from database
