### ISSUE TITLE
Sanitize HTML entered by user in editor/descriptions

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#11]
Since many fields (especially in the mission details) allow for content to be displayed as HTML, we have to add HTML sanitizing to prevent malicious code being executed or user information stolen via mission descriptions or likewise.

An example package for achieving this would be [sanitize-html](https://www.npmjs.com/package/sanitize-html).

This should definitely be added before the beta version of slotlist.info goes live and users start creating custom missions.

-----

### Tasks
- [ ] Include `sanitize-html` in backend model saving
- [ ] Define list of allowed tags and attributes (in combination with quill editor)
- [ ] Make sure every input that gets rendered as HTML is properly sanitized

**Comment by MorpheusXAUT** [comment]
It looks like some sort of sanitization is already done, presumably by the quill editor or vue... A few tests were not able to run any alerts or logs, so it might be enough already. This will need to be monitored though...

Postponed for now.

**Comment by MorpheusXAUT** [comment]
Sinus wasn't able to trigger any sort of vulnerability by manually spamming the site with garbage data or common attacks. This issue will be closed for now, since it appears the site is secure enough.
