### ISSUE TITLE
Set up PgHero to monitor Postgres performance

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#13]
[PgHero](https://github.com/ankane/pghero) provides a performance dashboard as well as some recommendations and monitoring for Postgres databases. An instance should be added to the k8s cluster to monitor the current queries and make sure all bottlenecks get adressed appropriately.

-----

### Tasks
- [x] Configure required Postgres extensions, permissions and tables
- [x] Set up PgHero instance and secure it
- [x] ~Add scheduled PgHero tasks for historical data~

**Comment by MorpheusXAUT** [comment]
At the moment, `CronJob`s can only be created in a kubernetes cluster with alpha features enabled, which automatically gets deleted after 30 days in GCP. Due to this, PgHero is currently running without the historical data added.
