### ISSUE TITLE
Associate slot registrations with communities

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#15]
Shawalla suggested that slot registrations could be associated with communities instead of users directly. This would solve the issue of having to search all users (list of communities should be way shorter), makes communities more useful and generally fits the current MO of reserving a group of slots for a community.

Users from the selected community could freely register for the slot - registrations would be blocked for everyone else. This also requires a community search endpoint.

-----

### Tasks
- [x] Add model for mission slot registrations
- [x] Add endpoint for searching community list
- [x] Allow for slots to be reserved for certain communities
- [x] Allow registrations for restricted slots only for community members
