### ISSUE TITLE
Serve i18n for frontend

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#2]
https://github.com/MorpheusXAUT/slotlist-frontend/issues/6 requires translation files to be served as JSON via the API.

To allow for easier updates, translations should not be stored in a file on the app server, but retrieved from database. This enables changes to be made via a future admin panel without having to redeploy the whole application.

For easier setup, i18n changes should also be persisted to a file checked into this repository from time to time, e.g. as a SQL dump.

-----

### Tasks
- [x] Add `languages` and `i18n` models and tables
- [x] ~Migration all current English translations into new translation tables~
- [x] ~Add API endpoints for languages & respective translation files~
- [x] ~Create database dump of current translations~
- [ ] Remove now unneeded translation tables and models

**Comment by MorpheusXAUT** [comment]
As decided in https://github.com/MorpheusXAUT/slotlist-frontend/issues/6, i18n will only be done client-side, not involving any backend APIs or likewise.
The recently created models and tables can thus be removed again.
