### ISSUE TITLE
Add slotlist separation into groups

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#3]
As of now, all slots are stored (and displayed) in a single list without any sort of separation or grouping.
Since most missions include some sort of "hierarchy" and separation into different groups (such as squads, platoons, etc.), this should also be represented in the app.

In the current implementation, `MissionSlots` are directly associated with `Missions`. In order to allow for grouping, another model such as `MissionSlotGroups` should be introduced. A mission would have one or multiple `MissionSlotGroups`, one `MissionSlotGroup` would have one or multiple `MissionSlots`. The group would also store some additional information such as a common callsign, a name or likewise.

This change most likely requires breaking changes to the slotlist API endpoints, however since we're not on a fully functional/public release yet, the `/v1` API will be broken instead of bumping the version already. A notice will be posted to Discord anyways, just in case.

Due to the potentially uneven number of slots per group, proper pagination/limiting of slots to display will probably be removed, requiring for all slots to be loaded at once (via a slot group endpoint).

The related frontend task can be found here: https://github.com/MorpheusXAUT/slotlist-frontend/issues/7

-----

### Tasks
- [x] Create `MissionSlotGroup` model and table
- [x] Update current associations with mission/slot models
- [x] Modify mission slot creation to also support groups
- [x] Add API endpoint for mission slot group creation/deletion
