### ISSUE TITLE
Implement permission granting/revoking for communities

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#37]
The backend already supports permissions for communities, but there's currently no way to grant a permission to a user (without adding a database row directly). #36 implemented this for missions, communities should be added as well.

-----

### Tasks
- [x] Add endpoint for retrieving community-related permissions
- [x] Add endpoint for granting community permissions
- [x] Add endpoint for revoking community permissions
