### ISSUE TITLE
Image upload/processing

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#4]
Whilst the current mission description editor allows for images to be "uploaded", they are only created to image data URIs and stored as "text" in the description and database. This can lead to large descriptions and higher database storage requirements as well as longer loading times.
Furthermore, new features such as https://github.com/MorpheusXAUT/slotlist-frontend/issues/8 could add more requirements for image uploads and storage.

Thus, the backend should handle image uploads, process the images received via the mission editor (parse the description for image data URIs, store the image separately and replace it with a link) and serve them separately.

Image storage could either be implemented in database (higher database storage requirements, slower loading times) or a storage provider such as GCP file storage ([code example](https://cloud.google.com/nodejs/getting-started/using-cloud-storage)). File uploads can be handled by hapi [directly](https://scotch.io/bar-talk/handling-file-uploads-with-hapi-js).

GCP pricing still has to be evaluated, it does look like the best candidate as of now though.

Since this requires more work, the feature will probably not be included in the `1.0.0-beta` release, but a later version.

-----

### Tasks
- [x] Evaluate storage options
- [x] Implement image upload
- [x] Implement parsing of image data URIs from descriptions
- [x] Implement storing of images in selected datastore
- [x] Serving of images from selected datastore
