### ISSUE TITLE
Added flag to block slot

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#46]
Blocking a slot disallows registrations while not requiring a user to be assigned already. This will be used to provide "manual" slot assignments of non-slotlist.info users.

-----

### Tasks
- [x] Add `blocked` flag to MissionSlot model
- [x] Add migration adding the required database column
- [x] Add check for blocked slots to all registration/assignment functionality
