### ISSUE TITLE
Add "visibility" setting for missions

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#5]
A "visibility" setting for missions could be implemented as follows:

1. `hidden`: mission only visible to mission creator and editors (default, can be used to hide mission while still working on description/slotlist)
2. `private`: mission only visible to selected users (not implemented in first release, only drafted for later)
3. `community`: mission only visible to members of the mission creator's community (setting not available if creator is not in a community, missions should be switched to `hidden` visibility if creator leaves community)
4. `public`: mission is visible to every user

For the first implementation (excluding the `private` visibility setting), a simple `visibility` enum for the `Mission` model is sufficient - additional checks have to be implemented when retrieving missions for a user.

In a later release, the `private` visibility setting will require a separate table for storing mission access.

-----

### Tasks
- [x] Add `visibility` enum to `Mission` model
- [x] Implement check for visibility setting upon retrieving mission list
- [x] Implement check for visibility setting upon retrieving mission details (404 for missions the user cannot "see")
- [x] Implement check for visibility setting upon retrieving mission slotlist/extended details (404 for missions the user cannot "see")
- [x] Allow for visibility to be changed upon mission creation/editing
