### ISSUE TITLE
Add option to ban users

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#54]
Users can currently not be banned or removed from the website. Deleting their account does not help in that regard either, so a flag or status should be added that disallows authentication with their Steam ID, effectively locking them out.

-----

### Tasks
- [x] Add flag for banned users
- [x] Add endpoint to ban users
- [x] Check user bans on authentication
