### ISSUE TITLE
Mission slot templates

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#59]
Many missions by the same community use similar - if not identical - slotlists. It would thus be useful to create templates for slotlists, allowing easy re-use of previously defined slotlists in new missions. This would also drastically speed up creation of new missions since creating the same slots over and over again is a bit... tedious.
Optionally, default templates could be added as well.

-----

### Tasks
- [x] Add mission slot template model
- [x] Add endpoint for retrieving mission slot template list
- [x] Add endpoint for retrieving mission slot template details
- [x] Add endpoint for creating a mission slot template
- [x] Add endpoint for updating a mission slot template
- [x] Add endpoint for deleting a mission slot template
- [x] Add template handling for slot creation
- [x] ~~Add default templates~~
