### ISSUE TITLE
Improve open mission slot count in mission list

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#62]
The open mission slot count in the mission list currently also includes restricted slots. These shouldn't be counted if the user does not have the permission to register for the slot (e.g. unauthenticated users or users from a different community).
Furthermore, the information displayed should be improved, including data about number of slots with registrations and number of reserve slots.

-----

### Tasks
- [x] Remove restricted slots from open slot count for users without "access"
- [x] Add count of slots with registrations
- [x] Add count of `reserve` slots
