### ISSUE TITLE
Implement notification system

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#70]
As suggested in https://github.com/MorpheusXAUT/slotlist-frontend/issues/107, an on-site system to notify users of important "events" (e.g. new slot application, new community application, any application accepted, etc) would be useful to have.
Since we do not have any way to send notifications to a user, we'll simply have a notification "list" on the site and a notification "indicator" e.g. on the nav bar.
Once a notification has been seen (loaded in a list), it should be marked as read and thus not show up in the notification indicator anymore. Alternatively, a "mark as seen" button could be added.

-----

### Tasks
- [x] Add `Notification` model
- [x] Add notification count endpoint
- [x] Add notification list endpoint
- [x] Implement marking notifications as read while retrieving or via manual endpoint
- [x] Implement notification creation for all relevant events
- [x] Test all implemented notifications

**Comment by MorpheusXAUT** [comment]
Missing notifications: `community.deleted`, `mission.deleted`, `mission.updated`
