### ISSUE TITLE
Move hosting to k8s in GCP

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#8]
The current self-hosted Docker infrastructure in GCP should be replaced with a container engine/k8s instance. Once again, traefik will be used as a loadbalancer in combination with nginx for service the frontend. A persistent disk for the Postgres container has to be added.

Since there's not much data stored at the moment anyways, the database migration could probably be skipped. The LetsEncrypt certificates requested by the current traefik instance should be backed up and reused (or revoked before terminating the old instance to avoid issues).

Regner's cloudbuild and k8s files can be used as a reference: [albionmarket-frontend](https://github.com/Regner/albionmarket-frontend) [albionmarket-backend](https://github.com/Regner/albionmarket-backend) (Thank you :smile: )

-----

### Tasks
- [x] Deploy k8s instance & configure basic setup
- [x] Add Postgres container with persistent disk
- [x] Add backend container ~with scaling/update rollout policy~
- [x] Add frontend container with scaling/update rollout policy
- [x] Add traefik container with proper routing configuration
- [x] Create cloudbuild tasks & container builder setup for backend and frontend
