### ISSUE TITLE
Add mission token as authentication alternative

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#80]
In order to build an integration into different forum systems, a different authentication method needs to be provided to access non-public missions.
One idea suggested generating (unique) tokens per mission and providing a URL parameter-passed authentication "alternative". This way, mission editors can embed their non-public mission in a forum post or homepage.

Relevant endpoints would be (for now):
- `GET /v1/missions/{missionSlug}`
- `GET /v1/missions/{missionSlug}/slots`

-----

### Tasks
- [x] Add mission API token to models
- [x] Implemented authentication "alternative" using mission API token (passed via header or URL parameter)
- [x] Implemented proper data retrieval for mentioned endpoints
- [x] Add endpoint for retrieving and generating mission tokens
