### ISSUE TITLE
Add server/TS IP to mission data

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#84]
Additional column for a server and/or TS IP could be useful to have, providing even more information and optionally allowing for auto-join links to be created in the frontend.

-----

### Tasks
- [x] Add server data
- [x] Add TS data
- [x] Update existing endpoints to allow for value modification
