### ISSUE TITLE
Add default server/TS/repo information to community model

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#85]
In extension of #84, default information for gameservers, TS or repos could be added to the community model, allowing for quick and easy creation without having to copy/paste the same data for every mission.
This could potentially include a list for each setting, allowing a mission creator to choose the entry appropriate for this mission.
The additional community information should be editable by community creators as well as leaders.

-----

### Tasks
- [x] Add default mission info to community model
- [x] Update community endpoints to allow for data modification
- [x] Add endpoint to return default mission info for usage in mission creation
