### ISSUE TITLE
Add logo to community model

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#9]
Backend-Task for https://github.com/MorpheusXAUT/slotlist-frontend/issues/15, adding a logo URL to the `Community` model. Just like the frontend task, this relies on #4 as a general image upload feature, most likely using GCP file storage as a storage backend.

Once uploaded and processed, only the logo URL should be stored in the community model attributes - with the image being fetched by the frontend upon loading appropriate pages.

Restrictions for image sizes have to be added as well.

Since this requires more work, the feature will probably not be included in the 1.0.0-beta release, but a later version.

-----

### Tasks
- [x] Add logo URL attribute to `Community` model
- [x] Process uploaded logo image and save in storage backend
- [x] Enforce appropriate restrictions for image dimensions and size
