### ISSUE TITLE
PDF upload for missions

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#92]
As suggested by Isaac, a PDF upload for missions would be nice to have for additional briefing documents. This would be especially useful in combination with #89 (for content caching to reduce traffic) and #90 (to restrict uploaded info to leadership slots).

The current image service would need to be abstracted to work as a general file storage service, allowing uploads of different file extensions as well. Different restrictions for filesizes etc. need to be added for PDFs and likewise as well.

-----

### Tasks
- [ ] Refactor ImageService to general StorageService
- [ ] Add upload endpoint for mission PDFs
- [ ] Define restrictions for mission PDF uploads
