### ISSUE TITLE
Add DLC requirements to missions/slots

### ISSUE THREAD

**Issue by MorpheusXAUT** [MorpheusXAUT/slotlist-backend#93]
As suggested in https://github.com/MorpheusXAUT/slotlist-frontend/issues/131, some missons (or only specific slots within the mission) could require a certain ArmA3 DLC (e.g. Heli-DLC, Tanoa, etc.).
The mission list endpoint could also be extended to allow filtering for certain DLCs.

DLC requirements would be indicators (maybe using little icons, as suggested) for now, but could potentially be extended in the future (e.g. users selecting which DLCs they have for automatic slot/mission filtering).

-----

### Tasks
- [x] Add DLC requirement flags to mission
- [x] Add DLC requirement flags to mission slot
- [x] ~Extend mission list endpoint to allow filter for DLCs~

**Comment by MorpheusXAUT** [comment]
Filtering is done on the frontend for now - can be added to the mission list endpoint later if required.
